name: webf_cupertino_ui_example
description: Example app demonstrating WebF Cupertino UI components
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # For development: use local webf package
  # For publishing: uncomment below and comment out the path dependency above
  webf:
    hosted: https://dart.cloudsmith.io/openwebf/webf-enterprise/
    version: ^0.22.0
  webf_cupertino_ui:
    path: ../

dependency_overrides:
  webf:
    path: ../../webf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Include the example HTML files
  assets:
    - assets/
