name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Dry run
      run: flutter pub publish --dry-run
    
    - name: Publish
      uses: sakebook/actions-flutter-pub-publisher@v1.4.1
      with:
        credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
        flutter_package: true
        skip_test: true